// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb8OQSHg25TnkXFGXiiDF-Ci845eQwE-k',
    appId: '1:276017534402:android:d8dbf445ae4da00bd4f25b',
    messagingSenderId: '276017534402',
    projectId: 'animal-sounds-a0c5b',
    storageBucket: 'animal-sounds-a0c5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPxZKWF5v23jA-UYI4-OzpmRiKu0MVtkA',
    appId: '1:276017534402:ios:005f17e82acc1ef3d4f25b',
    messagingSenderId: '276017534402',
    projectId: 'animal-sounds-a0c5b',
    storageBucket: 'animal-sounds-a0c5b.appspot.com',
    iosClientId: '276017534402-i9sbo9ar20nhh3tba9jqb3p16kgjcqb0.apps.googleusercontent.com',
    iosBundleId: 'droid.personal.animalsoun',
  );
}
